db:
  uri: "mongodb://127.0.0.1:27017/api_server"
  user: "waxh"
  pass: "ysp@1234"

mysql:
  host: "127.0.0.1"
  database: "websiteManager"
  user: "root"
  password: "Waxh@sql@1234"
  dialect: 'mysql'
  pool:
    max: 5
    min: 0
    acquie: 30000
    idle: 10000
  # 同步模型到数据库
  needCreatTable: false
  # 同步前清空所有旧表
  dropOldTable: false

# fs.mkdir不能一次创建多级目录，必须确保上一级目录已经存在
uploadRootPath: "/project/nginx/html/uploads/"
