db:
  uri: "mongodb://49.234.158.74:27017/api_server_waxh"
  user: "waxh"
  pass: "ysp@1234"

mysql:
  host: "www.snains.cn"
  database: "websiteManager"
  user: "root"
  password: "10isp.com!a"
  dialect: 'mysql'
  pool:
    max: 5
    min: 0
    acquie: 30000
    idle: 10000
  needCreatTable: false

oldManager: "http://www.snains.cn:9001"

# fs.mkdir不能一次创建多级目录，必须确保上一级目录已经存在
uploadRootPath: "/usr/share/nginx/html/uploads/"