db:
  uri: "mongodb://localhost:27017/api_server_waxh"
  user: "waxh"
  pass: "ysp@1234"

mysql:
  host: "117.34.74.241"
  database: "websiteManager"
  user: "root"
  password: "fe741f398fc5010b"
  dialect: 'mysql'
  pool:
    max: 5
    min: 0
    acquie: 30000
    idle: 10000
  needCreatTable: false

uploadRootPath: "/usr/share/nginx/html/uploads/"

# 加密key
HMAC_KEY: "+JLrGABkuDsz2HPriUGNdtNnP/TBlAX8THiQF7eYoH"