db:
  uri: "mongodb://localhost:27017/api_server_waxh"
  user: "waxh"
  pass: "ysp@1234"

mysql:
  host: "localhost"
  database: "websiteManager"
  user: "root"
  password: "10isp.com!a"
  dialect: 'mysql'
  pool:
    max: 5
    min: 0
    acquie: 30000
    idle: 10000
  needCreatTable: false

oldManager: "http://localhost:9001"